server.port=${AUTH_SERVER_PORT}

keycloak.realm=${KEYCLOAK_REALM}
keycloak.auth-server-url=${KEYCLOAK_AUTH_SERVER_URL}
keycloak.resource=${KEYCLOAK_RESOURCE}
keycloak.credentials.secret=${KEYCLOAK_CLIENT_SECRET}
client-id=${KEYCLOAK_CLIENT_ID}

spring.datasource.url=${KeyCloak_DB_URL}
spring.datasource.username=${KeyCloak_DB_USERNAME}
spring.datasource.password=${KeyCloak_DB_PASSWORD}

spring.jpa.properties.hibernate.default_schema=${KeyCloak_DB_SCHEMA}

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${JWT_JWK_SET_URI}
